### ISSUE TITLE
Integration tests are failing in IE11

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-custom-field-flow#45]
Starting from the WC version bump to 1.0.8 the build is failing

```
[13:17:27][Step 3/7] [ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 82.879 s <<< FAILURE! - in com.vaadin.flow.component.customfield.test.BasicIT
[13:17:27][Step 3/7] [ERROR] valueIsUpdated[WIN8_1_InternetExplorer_](com.vaadin.flow.component.customfield.test.BasicIT)  Time elapsed: 54.935 s  <<< ERROR!
[13:17:27][Step 3/7] org.openqa.selenium.TimeoutException: 
[13:17:27][Step 3/7] Expected condition failed: waiting for com.vaadin.testbench.ElementQuery$$Lambda$457/548150015@5a5c158a (tried for 10 second(s) with 500 milliseconds interval)
[13:17:27][Step 3/7] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
[13:17:27][Step 3/7] System info: host: 'ip-172-16-1-42.eu-west-1.compute.internal', ip: '172.16.1.42', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.123-111.109.amzn2.x86_64', java.version: '1.8.0_201'
[13:17:27][Step 3/7] Driver info: com.vaadin.testbench.TestBenchDriverProxy_$$_jvstadb_0
[13:17:27][Step 3/7] Capabilities {browserAttachTimeout: 0, browserName: internet explorer, cssSelectorsEnabled: true, elementScrollBehavior: 0, enableElementCacheCleanup: true, enablePersistentHover: true, hasMetadata: true, ie.browserCommandLineSwitches: , ie.enableFullPageScreenshot: true, ie.ensureCleanSession: true, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ie.forceShellWindowsApi: false, ignoreProtectedModeSettings: false, ignoreZoomSetting: false, initialBrowserUrl: about:blank, javascriptEnabled: true, nativeEvents: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, requireWindowFocus: false, takesScreenshot: true, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss, version: 11, webdriver.remote.sessionid: 72d6ebea271349788912a176b9e...}
[13:17:27][Step 3/7] Session ID: 72d6ebea271349788912a176b9e6ed95
[13:17:27][Step 3/7] 	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
[13:17:27][Step 3/7] 	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
[13:17:27][Step 3/7] 	at com.vaadin.testbench.ElementQuery.waitForFirst(ElementQuery.java:257)
[13:17:27][Step 3/7] 	at com.vaadin.flow.component.customfield.test.BasicIT.valueIsUpdated(BasicIT.java:19)
[13:17:27][Step 3/7] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:17:27][Step 3/7] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:17:27][Step 3/7] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:17:27][Step 3/7] 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:17:27][Step 3/7] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[13:17:27][Step 3/7] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[13:17:27][Step 3/7] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[13:17:27][Step 3/7] 	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:494)
[13:17:27][Step 3/7] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[13:17:27][Step 3/7] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[13:17:27][Step 3/7] 	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:468)
[13:17:27][Step 3/7] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
[13:17:27][Step 3/7] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[13:17:27][Step 3/7] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[13:17:27][Step 3/7] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[13:17:27][Step 3/7] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[13:17:27][Step 3/7] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[13:17:27][Step 3/7] 	at com.vaadin.testbench.parallel.ParallelScheduler$1.call(ParallelScheduler.java:48)
[13:17:27][Step 3/7] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:17:27][Step 3/7] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:17:27][Step 3/7] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:17:27][Step 3/7] 	at java.lang.Thread.run(Thread.java:748)
[13:17:27][Step 3/7] 
[13:17:28][Step 3/7] [INFO] 
[13:17:28][Step 3/7] [INFO] Results:
[13:17:28][Step 3/7] [INFO] 
[13:17:28][Step 3/7] [ERROR] Errors: 
[13:17:28][Step 3/7] [ERROR]   BasicIT.valueIsUpdated:19 » Timeout Expected condition failed: waiting for com...
[13:17:28][Step 3/7] [INFO] 
[13:17:28][Step 3/7] [ERROR] Tests run: 10, Failures: 0, Errors: 1, Skipped: 5
```

**Comment by web-padawan** [comment]
The snapshots are green now, so this seems to be no longer relevant. Closing.
